"""Tests for provenance: hashes come from runs, never from hands."""

import hashlib

import numpy as np

from spectral_diag.provenance import generate_record
from spectral_diag.service import SpectralService


def _fixture():
    D = np.zeros((32, 32))
    for i in range(8):
        D[i, i + 8] = D[i + 8, i] = 0.5
        D[i + 16, i + 24] = D[i + 24, i + 16] = 0.5
    return D


def test_meta_carries_input_hash():
    svc = SpectralService(engine_name="lean32")
    A = _fixture()
    res = svc.diagnose(A, {})
    assert res.meta["input_hash"] == svc._key(A, {}), "meta hash must equal _key of actual bytes"


def test_input_hash_verifies_against_bytes():
    # Independent recomputation from the raw bytes: the definition of the hash.
    A = np.ascontiguousarray(_fixture(), dtype=float)
    expected_hex = hashlib.sha256(A.tobytes()).hexdigest()
    svc = SpectralService(engine_name="lean32")
    key = svc._key(A, {})
    assert key == f"lean32:{expected_hex}:[]", "key format or bytes mismatch"


def test_input_hash_changes_with_bytes():
    svc = SpectralService(engine_name="lean32")
    A, B = _fixture(), _fixture()
    B[0, 0] = 1e-6  # one-bit-level change
    assert svc.diagnose(A, {}).meta["input_hash"] != svc.diagnose(B, {}).meta["input_hash"]


def test_generate_record_is_tool_generated():
    rec = generate_record(_fixture(), "lean32", {})
    assert "GENERATED BY TOOL" in rec
    assert "physical_experiment_occurred: false" in rec
    assert "input_hash_computed_from_actual_bytes: true" in rec
    # hash in the record matches an independent run of the same bytes
    svc = SpectralService(engine_name="lean32")
    assert svc._key(np.asarray(_fixture()), {}) in rec


def test_generate_record_flags_unstamped_engine_version():
    # lean32 exposes no version attribute: the record must say so, not invent one.
    rec = generate_record(_fixture(), "lean32", {})
    assert "UNSTAMPED" in rec
    assert "v0.2.1" not in rec
