"""Provenance record generator.

The record is generated by the tool from an actual run — never typed by hand.
Every field the tool can know is computed from the real input bytes; everything
else is explicitly marked as operator-declared (unverified) or PENDING.

An invented hash is worse than a placeholder because it looks like evidence.
So: no field here is ever hand-filled. If the run didn't happen, there is no
record.
"""

from datetime import datetime, timezone
from typing import Any, Dict, Optional

import numpy as np

from .service import SpectralService

try:
    from . import __version__ as _SERVICE_VERSION
except Exception:  # pragma: no cover - defensive
    _SERVICE_VERSION = "unknown"


def _input_class(A: np.ndarray) -> str:
    kind = str(A.dtype)
    if np.allclose(A, A.conj().T):
        kind += " Hermitian"
    elif np.allclose(A, A.T):
        kind += " real-symmetric"
    else:
        kind += " non-symmetric"
    return kind


def _engine_version(svc: SpectralService) -> str:
    eng = svc.engine
    if eng is None:
        return "n/a (reference fallback)"
    v = getattr(eng, "version", None) or getattr(eng, "__version__", None)
    if v:
        return str(v)
    return "UNSTAMPED (engine exposes no version attribute)"


def generate_record(
    A: np.ndarray,
    engine_name: Optional[str] = None,
    params: Optional[Dict[str, Any]] = None,
    run_id: Optional[str] = None,
) -> str:
    """Run the diagnostic on the actual bytes and return a provenance record.

    The input_hash in the record IS svc._key() of the bytes that were
    diagnosed — recompute it any time from the same array to verify.
    """
    params = params or {}
    svc = SpectralService(engine_name=engine_name)
    A = np.asarray(A)
    res = svc.diagnose(A, params)  # the run itself; hash comes from these bytes
    input_hash = res.meta["input_hash"]
    assert input_hash == svc._key(A, params), "hash/run mismatch (internal error)"

    # short id from the hash itself, so the id can't drift from the bytes
    hexpart = input_hash.split(":")[1] if ":" in input_hash else "unknown"
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    record_id = run_id or f"sd-run-{stamp}-{hexpart[:8]}"

    lines = [
        "# spectral-diag / provenance record",
        "# Status: GENERATED BY TOOL — computation run metadata, not a verified physical experiment",
        f"record_id:         {record_id}",
        "record_type:       computation_run_metadata",
        f"generated_by:      spectral provenance (spectral-diag {_SERVICE_VERSION})",
        "",
        "# Computation identity — every value below computed from the actual run",
        f"engine:            {svc.engine_name or 'fallback'}",
        f"engine_version:    {_engine_version(svc)}",
        f"service_version:   spectral-diag {_SERVICE_VERSION}",
        "entry_point:       spectral_diag.service.SpectralService.diagnose",
        f"input_hash:        {input_hash}",
        f"input_dtype:       {A.dtype}",
        f"input_shape:       {A.shape}",
        f"input_class:       {_input_class(A)}",
        "byte_order:        C (numpy tobytes default)",
        f"run_time_utc:      {datetime.now(timezone.utc).isoformat()}",
        f"params:            {params!r}",
        "",
        "# How to re-verify input_hash",
        "verify: |",
        "  input_hash = f\"{engine}:{sha256(A.tobytes())}:{repr(sorted(params.items()))}\"",
        "  where A is the exact input array (same dtype, shape, C-order bytes).",
        "  Any byte-level difference changes the hash. If it doesn't match,",
        "  the record does not describe your bytes.",
        "",
        "# Declared by operator — NOT verified by the tool",
        "declared_location: PENDING_OPERATOR",
        "declared_time_local: PENDING_OPERATOR",
        "",
        "# Scope note — read before citing",
        "claims:",
        "  physical_experiment_occurred: false",
        "  computation_was_run:          true",
        "  input_hash_computed_from_actual_bytes: true",
        "  location_verified:            false",
        "  time_verified:                false",
        "notes: |",
        "  This record was generated by the tool from the bytes it diagnosed.",
        "  It does not attest that a physical experiment took place anywhere,",
        "  nor where the hardware ran. Declared location/time are the",
        "  operator's own statements, not tool-verified facts. Numerical",
        "  results are reproducible from the engine, version, and input hash",
        "  above regardless of where they executed.",
    ]
    return "\n".join(lines)
